collated: false
variants:
- name: default
  context:
    content: "<p>The power of the Web is in its universality.<br>Access by everyone regardless of disability is an essential aspect.</p><p>Another paragraph. Just for illustration purposes.</p>"
    source: "Tim Berners-Lee, W3C Director and inventor of the World Wide Web"
- name: special
  context:
    class: special
    content: "<p>The power of the Web is in its universality.<br>Access by everyone regardless of disability is an essential aspect.</p><p>Another paragraph. Just for illustration purposes.</p>"
    source: "Tim Berners-Lee, W3C Director and inventor of the World Wide Web"
- name: Pullquote
  context:
    class: pull
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
- name: Pullquote Left
  context:
    class: pull left
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
- name: Pullquote Right
  context:
    class: pull right
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
- name: Pullquote Color Alt 1
  context:
    class: pull alt-1 right
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
- name: Pullquote Color Alt 2
  context:
    class: pull alt-2 right
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
- name: Pullquote Color Alt 3
  context:
    class: pull alt-3 right
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
- name: Pullquote in box
  context:
    class: pull right
    box: true
    content: "<p>I do what I do because it’s right! Because it’s decent! And above all, it’s kind! It’s just that…</p>"
    source: "John Smith, TARDIS Inc."
