status: wip
default: default
variants:
- name: default
  context:
    label: Standard header
- name: large
  context:
    label: Large Header
    mods: ['large']
- name: large-icon
  context:
    type: icon
    label: Large Header w/ Icon
    icon: warning
    mods: ['large','icon']
- name: simple
  context:
    label: Simple header w/o bg and less spacing
    mods: ['simple']